language: generic

matrix:
  include:
     - { os: linux, env: PYTHON_VERSION=2.7 }
     - { os: linux, env: PYTHON_VERSION=3.4 }
     - { os: linux, env: PYTHON_VERSION=3.5 }
     # - { os: osx, env: PYTHON_VERSION=3.5 }

sudo: false

before_install:
  - 
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew tap homebrew/science;
      brew update;
      brew install netcdf fftw;
    fi

install:
    - npm install -g nightwatch
    - source devtools/travis-ci/setup_env.sh
    - source devtools/travis-ci/clone_nbtest.sh
    - ls
    - python setup.py install

before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - sleep 3
    - jupyter notebook --port=8889 &
    - sleep 3

script:
    - nightwatch
    - (cd nglview/tests && nosetests --with-coverage --cover-package nglview -vs .)

after_success:
    - echo "after_success"
    # - coveralls

notifications:
  email: false
