language: generic

matrix:
  include:
     - { os: linux, env: PYTHON_VERSION=2.7 }
     - { os: linux, env: PYTHON_VERSION=3.4 }
     - { os: linux, env: PYTHON_VERSION=3.5 }
     - { os: osx, env: PYTHON_VERSION=3.5 }

sudo: false

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew tap homebrew/science;
      brew update;
      brew install netcdf fftw;
    fi

install:
    - source devtools/travis-ci/setup_env.sh
    - python setup.py install

script:
    - nosetests --with-coverage --cover-package nglview -vs .

after_success:
    - echo "after_success"
    # - coveralls

notifications:
  email: false
