matrix:
  include:
     - { os: linux, env: PYTHON_VERSION=3.7 }
     - { os: linux, env: PYTHON_VERSION=3.6 }

install:
    - source devtools/travis-ci/setup_env.sh
    - source devtools/travis-ci/install_nglview.sh

script:
    - (cd nglview/tests && pytest --cov=nglview -vs .)
      # - source devtools/travis-ci/run_tests.sh

after_success:
    - echo "Congrats"
    - (cd nglview/tests && ../../devtools/travis-ci/coveralls)

notifications:
  email: false
