language: cpp

matrix:
  include:
     - { os: linux, env: PYTHON_VERSION=3.7 }
     - { os: linux, env: PYTHON_VERSION=3.6 }

sudo: true
dist: trusty

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - clang-3.6
    - unzip

before_install:
    - source devtools/travis-ci/install_chrome.sh
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        brew tap homebrew/science;
        brew update;
        brew install netcdf fftw;
      fi

install:
    - source devtools/travis-ci/setup_env.sh
    - source devtools/travis-ci/clone_nbtest.sh
    - source devtools/travis-ci/install_nglview.sh

script:
    # Not run in root folder to avoid wrongfully report the coverage
    - (cd nglview/tests && pytest -vs . --cov=nglview --cov-report=html --disable-pytest-warnings)

after_success:
    - echo "Congrats"
    - (cd nglview/tests && coveralls)

notifications:
  email: false
