language: cpp

matrix:
  include:
     - { os: linux, env: PYTHON_VERSION=2.7 }
     - { os: linux, env: PYTHON_VERSION=3.4 }
     - { os: linux, env: PYTHON_VERSION=3.5 }
     - { os: linux, env: PYTHON_VERSION=3.5 CONDA=yes}
     # - { os: osx, env: PYTHON_VERSION=3.5 }

sudo: true
dist: trusty

addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test
    packages:
    # install toolchains
    - gcc-5
    - g++-5
    - clang-3.6
    - unzip
    # - google-chrome-stable

before_install:
    - source devtools/travis-ci/install_chrome.sh
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        brew tap homebrew/science;
        brew update;
        brew install netcdf fftw;
      fi

install:
    - npm install -g nightwatch
    - source devtools/travis-ci/setup_env.sh
    - source devtools/travis-ci/clone_nbtest.sh
    - source devtools/travis-ci/install_nglview.sh

before_script:
    - source devtools/travis-ci/open_notebook.sh

script:
    - (cd nglview/tests && nosetests --with-coverage --cover-package nglview -vs .)

after_success:
    - echo "after_success"
    # - coveralls

notifications:
  email: false
