name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash -l {0}

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2

    - name: Cache conda
      uses: actions/cache@v1
      env:
        CACHE_NUMBER: 0  # Increase this value to reset cache if environment.yml has not changed
      with:
        path: ~/conda_pkgs_dir
        key:
          ${{ matrix.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('environment.yml') }}

    - uses: conda-incubator/setup-miniconda@v2
      with:
          auto-update-conda: true
          auto-activate-base: false
          activate-environment: nglview
          environment-file: environment.yml
          channel-priority: true
          python-version: ${{ matrix.python-version }}
          use-only-tar-bz2: true  # IMPORTANT: This needs to be set for caching to work properly!

    - run: |
        conda info
        conda list
